[phases.setup]
nixPkgs = [
  "nodejs_22",
  "npm-10_x",
  "php84",
  "php84Packages.composer",
  "php84Extensions.zip",
  "php84Extensions.gd",
  "php84Extensions.xml",
  "php84Extensions.dom",
  "php84Extensions.fileinfo",
  "php84Extensions.mbstring",
  "php84Extensions.sqlite3",
  "php84Extensions.pdo_sqlite",
  "php84Extensions.pgsql",
  "php84Extensions.pdo_pgsql",
  "nginx"
]

[phases.setup.variables]
NIXPACKS_PHP_NGINX_CONFIG_FILE = "nginx.template.conf"
NIXPACKS_PHP_ROOT_DIR = "/app/public"
NIXPACKS_PHP_INI_FILE = "php.ini"

[phases.build]
cmds = ["...", "cp php.ini /etc/php84/conf.d/99-custom.ini 2>/dev/null || true", "php artisan optimize", "php artisan storage:link"]
