/** Content for the Hints (charades) game: act it out, no words allowed. */

export type CharadesCategory =
    | 'Actie'
    | 'Dier'
    | 'Beroep'
    | 'Voorwerp'
    | 'Sport'
    | 'Film & TV'
    | 'Beroemd'
    | 'Emotie';

export interface CharadesCard {
    /** What the player must act out. */
    word: string;
    /** A small hint for the guessers, shown on the card. */
    category: CharadesCategory;
}

export const CARDS: CharadesCard[] = [
    { word: 'Tandenpoetsen', category: 'Actie' },
    { word: 'Stofzuigen', category: 'Actie' },
    { word: 'Douchen', category: 'Actie' },
    { word: 'Autorijden', category: 'Actie' },
    { word: 'Vissen', category: 'Actie' },
    { word: 'Breien', category: 'Actie' },
    { word: 'Gitaar spelen', category: 'Actie' },
    { word: 'Slapen', category: 'Actie' },
    { word: 'Niezen', category: 'Actie' },
    { word: 'Verhuizen', category: 'Actie' },
    { word: 'Bankoverval', category: 'Actie' },
    { word: 'Selfie maken', category: 'Actie' },
    { word: 'Parachutespringen', category: 'Actie' },
    { word: 'Solliciteren', category: 'Actie' },
    { word: 'Hik hebben', category: 'Actie' },
    { word: 'Taart bakken', category: 'Actie' },
    { word: 'Band plakken', category: 'Actie' },
    { word: 'Luier verschonen', category: 'Actie' },
    { word: 'Parallel parkeren', category: 'Actie' },
    { word: 'Aanzoek doen', category: 'Actie' },
    { word: 'Afwassen', category: 'Actie' },
    { word: 'Strijken', category: 'Actie' },
    { word: 'Ramen lappen', category: 'Actie' },
    { word: 'Haren föhnen', category: 'Actie' },
    { word: 'Nagels lakken', category: 'Actie' },
    { word: 'Scheren', category: 'Actie' },
    { word: 'Schoenveters strikken', category: 'Actie' },
    { word: 'Koffie zetten', category: 'Actie' },
    { word: 'Pizza bezorgen', category: 'Actie' },
    { word: 'Ui snijden', category: 'Actie' },
    { word: 'Pannenkoek omdraaien', category: 'Actie' },
    { word: 'Spaghetti eten', category: 'Actie' },
    { word: 'Ballon opblazen', category: 'Actie' },
    { word: 'Cadeau inpakken', category: 'Actie' },
    { word: 'Kaarsjes uitblazen', category: 'Actie' },
    { word: 'Bloemen water geven', category: 'Actie' },
    { word: 'Gras maaien', category: 'Actie' },
    { word: 'Sneeuw ruimen', category: 'Actie' },
    { word: 'Bladeren harken', category: 'Actie' },
    { word: 'Hond uitlaten', category: 'Actie' },
    { word: 'Kat aaien', category: 'Actie' },
    { word: 'Paardrijden', category: 'Actie' },
    { word: 'Fietsen', category: 'Actie' },
    { word: 'Zwemmen', category: 'Actie' },
    { word: 'Roeien', category: 'Actie' },
    { word: 'Schaatsen', category: 'Actie' },
    { word: 'Skiën', category: 'Actie' },
    { word: 'Bergbeklimmen', category: 'Actie' },
    { word: 'Tent opzetten', category: 'Actie' },
    { word: 'Kampvuur maken', category: 'Actie' },
    { word: 'Liften', category: 'Actie' },
    { word: 'Koffer inpakken', category: 'Actie' },
    { word: 'Vliegtuig instappen', category: 'Actie' },
    { word: 'Zonnebaden', category: 'Actie' },
    { word: 'Duiken', category: 'Actie' },
    { word: 'Surfen', category: 'Actie' },
    { word: 'Zandkasteel bouwen', category: 'Actie' },
    { word: 'Sneeuwpop maken', category: 'Actie' },
    { word: 'Vuurwerk afsteken', category: 'Actie' },
    { word: 'Bier tappen', category: 'Actie' },
    { word: 'Proosten', category: 'Actie' },
    { word: 'Karaoke zingen', category: 'Actie' },
    { word: 'Dansen', category: 'Actie' },
    { word: 'Applaudisseren', category: 'Actie' },
    { word: 'Piano spelen', category: 'Actie' },
    { word: 'Drummen', category: 'Actie' },
    { word: 'Trompet spelen', category: 'Actie' },
    { word: 'Viool spelen', category: 'Actie' },
    { word: 'Schilderen', category: 'Actie' },
    { word: 'Tekenen', category: 'Actie' },
    { word: 'Typen', category: 'Actie' },
    { word: 'Telefoneren', category: 'Actie' },
    { word: 'Boodschappen doen', category: 'Actie' },
    { word: 'Pinnen', category: 'Actie' },
    { word: 'Wachten in de rij', category: 'Actie' },
    { word: 'Trap lopen', category: 'Actie' },
    { word: 'Op de bus wachten', category: 'Actie' },
    { word: 'Sok stoppen', category: 'Actie' },
    { word: 'Was ophangen', category: 'Actie' },
    { word: 'Spijker slaan', category: 'Actie' },
    { word: 'Kangoeroe', category: 'Dier' },
    { word: 'Slang', category: 'Dier' },
    { word: 'Kip', category: 'Dier' },
    { word: 'Aap', category: 'Dier' },
    { word: 'Olifant', category: 'Dier' },
    { word: 'Pinguïn', category: 'Dier' },
    { word: 'Krab', category: 'Dier' },
    { word: 'Luiaard', category: 'Dier' },
    { word: 'Flamingo', category: 'Dier' },
    { word: 'Kameleon', category: 'Dier' },
    { word: 'Vleermuis', category: 'Dier' },
    { word: 'Kwal', category: 'Dier' },
    { word: 'Specht', category: 'Dier' },
    { word: 'Stinkdier', category: 'Dier' },
    { word: 'Giraffe', category: 'Dier' },
    { word: 'Kikker', category: 'Dier' },
    { word: 'Konijn', category: 'Dier' },
    { word: 'Muis', category: 'Dier' },
    { word: 'Varken', category: 'Dier' },
    { word: 'Haan', category: 'Dier' },
    { word: 'Eend', category: 'Dier' },
    { word: 'Uil', category: 'Dier' },
    { word: 'Struisvogel', category: 'Dier' },
    { word: 'Papegaai', category: 'Dier' },
    { word: 'Haai', category: 'Dier' },
    { word: 'Dolfijn', category: 'Dier' },
    { word: 'Octopus', category: 'Dier' },
    { word: 'Zeehond', category: 'Dier' },
    { word: 'Schildpad', category: 'Dier' },
    { word: 'Krokodil', category: 'Dier' },
    { word: 'Leeuw', category: 'Dier' },
    { word: 'Tijger', category: 'Dier' },
    { word: 'Beer', category: 'Dier' },
    { word: 'Wolf', category: 'Dier' },
    { word: 'Neushoorn', category: 'Dier' },
    { word: 'Nijlpaard', category: 'Dier' },
    { word: 'Kameel', category: 'Dier' },
    { word: 'Egel', category: 'Dier' },
    { word: 'Eekhoorn', category: 'Dier' },
    { word: 'Mol', category: 'Dier' },
    { word: 'Vlinder', category: 'Dier' },
    { word: 'Bij', category: 'Dier' },
    { word: 'Spin', category: 'Dier' },
    { word: 'Mug', category: 'Dier' },
    { word: 'Slak', category: 'Dier' },
    { word: 'Worm', category: 'Dier' },
    { word: 'Kreeft', category: 'Dier' },
    { word: 'Zeester', category: 'Dier' },
    { word: 'Pauw', category: 'Dier' },
    { word: 'Gorilla', category: 'Dier' },
    { word: 'Kapper', category: 'Beroep' },
    { word: 'Tandarts', category: 'Beroep' },
    { word: 'Chirurg', category: 'Beroep' },
    { word: 'Dirigent', category: 'Beroep' },
    { word: 'Piloot', category: 'Beroep' },
    { word: 'Ober', category: 'Beroep' },
    { word: 'Scheidsrechter', category: 'Beroep' },
    { word: 'Bokser', category: 'Beroep' },
    { word: 'Goochelaar', category: 'Beroep' },
    { word: 'Loodgieter', category: 'Beroep' },
    { word: 'Slager', category: 'Beroep' },
    { word: 'Postbode', category: 'Beroep' },
    { word: 'Bouwvakker', category: 'Beroep' },
    { word: 'Fotograaf', category: 'Beroep' },
    { word: 'Glazenwasser', category: 'Beroep' },
    { word: 'Brandweerman', category: 'Beroep' },
    { word: 'Gevangenisbewaker', category: 'Beroep' },
    { word: 'Politieagent', category: 'Beroep' },
    { word: 'Bakker', category: 'Beroep' },
    { word: 'Kok', category: 'Beroep' },
    { word: 'Boer', category: 'Beroep' },
    { word: 'Visser', category: 'Beroep' },
    { word: 'Jager', category: 'Beroep' },
    { word: 'Soldaat', category: 'Beroep' },
    { word: 'Matroos', category: 'Beroep' },
    { word: 'Buschauffeur', category: 'Beroep' },
    { word: 'Taxichauffeur', category: 'Beroep' },
    { word: 'Treinconducteur', category: 'Beroep' },
    { word: 'Verkeersregelaar', category: 'Beroep' },
    { word: 'Schoonmaker', category: 'Beroep' },
    { word: 'Stukadoor', category: 'Beroep' },
    { word: 'Timmerman', category: 'Beroep' },
    { word: 'Smid', category: 'Beroep' },
    { word: 'Automonteur', category: 'Beroep' },
    { word: 'Kleermaker', category: 'Beroep' },
    { word: 'Schoenmaker', category: 'Beroep' },
    { word: 'Kassamedewerker', category: 'Beroep' },
    { word: 'Verpleegkundige', category: 'Beroep' },
    { word: 'Dierenarts', category: 'Beroep' },
    { word: 'Fysiotherapeut', category: 'Beroep' },
    { word: 'Leraar', category: 'Beroep' },
    { word: 'Bibliothecaris', category: 'Beroep' },
    { word: 'Rechter', category: 'Beroep' },
    { word: 'Advocaat', category: 'Beroep' },
    { word: 'Clown', category: 'Beroep' },
    { word: 'Danseres', category: 'Beroep' },
    { word: 'Balletdanser', category: 'Beroep' },
    { word: 'Nieuwslezer', category: 'Beroep' },
    { word: 'Astronaut', category: 'Beroep' },
    { word: 'Archeoloog', category: 'Beroep' },
    { word: 'Paraplu', category: 'Voorwerp' },
    { word: 'Schaar', category: 'Voorwerp' },
    { word: 'Ladder', category: 'Voorwerp' },
    { word: 'Wekker', category: 'Voorwerp' },
    { word: 'Hangmat', category: 'Voorwerp' },
    { word: 'Trampoline', category: 'Voorwerp' },
    { word: 'Kurkentrekker', category: 'Voorwerp' },
    { word: 'Blender', category: 'Voorwerp' },
    { word: 'Rolstoel', category: 'Voorwerp' },
    { word: 'Skateboard', category: 'Voorwerp' },
    { word: 'Rietje', category: 'Voorwerp' },
    { word: 'Zonnebrand', category: 'Voorwerp' },
    { word: 'Deurbel', category: 'Voorwerp' },
    { word: 'Kettingzaag', category: 'Voorwerp' },
    { word: 'Lift', category: 'Voorwerp' },
    { word: 'Rolgordijn', category: 'Voorwerp' },
    { word: 'Kruiwagen', category: 'Voorwerp' },
    { word: 'Verrekijker', category: 'Voorwerp' },
    { word: 'Vergrootglas', category: 'Voorwerp' },
    { word: 'Zaklamp', category: 'Voorwerp' },
    { word: 'Hamer', category: 'Voorwerp' },
    { word: 'Boormachine', category: 'Voorwerp' },
    { word: 'Schroevendraaier', category: 'Voorwerp' },
    { word: 'Fietspomp', category: 'Voorwerp' },
    { word: 'Tuinslang', category: 'Voorwerp' },
    { word: 'Bezem', category: 'Voorwerp' },
    { word: 'Dweil', category: 'Voorwerp' },
    { word: 'Stethoscoop', category: 'Voorwerp' },
    { word: 'Wasknijper', category: 'Voorwerp' },
    { word: 'Naaimachine', category: 'Voorwerp' },
    { word: 'Weegschaal', category: 'Voorwerp' },
    { word: 'Waaier', category: 'Voorwerp' },
    { word: 'Zonnebril', category: 'Voorwerp' },
    { word: 'Handboeien', category: 'Voorwerp' },
    { word: 'Megafoon', category: 'Voorwerp' },
    { word: 'Draaiorgel', category: 'Voorwerp' },
    { word: 'Schommel', category: 'Voorwerp' },
    { word: 'Glijbaan', category: 'Voorwerp' },
    { word: 'Wipwap', category: 'Voorwerp' },
    { word: 'Draaideur', category: 'Voorwerp' },
    { word: 'Roltrap', category: 'Voorwerp' },
    { word: 'Kauwgom', category: 'Voorwerp' },
    { word: 'IJsje', category: 'Voorwerp' },
    { word: 'Tandenstoker', category: 'Voorwerp' },
    { word: 'Kroonkurk', category: 'Voorwerp' },
    { word: 'Jojo', category: 'Voorwerp' },
    { word: 'Vlieger', category: 'Voorwerp' },
    { word: 'Strandbal', category: 'Voorwerp' },
    { word: 'Stelten', category: 'Voorwerp' },
    { word: 'Zwemband', category: 'Voorwerp' },
    { word: 'Bowlen', category: 'Sport' },
    { word: 'Darts', category: 'Sport' },
    { word: 'Golf', category: 'Sport' },
    { word: 'Boogschieten', category: 'Sport' },
    { word: 'Schermen', category: 'Sport' },
    { word: 'Judo', category: 'Sport' },
    { word: 'Turnen', category: 'Sport' },
    { word: 'Curling', category: 'Sport' },
    { word: 'Zumba', category: 'Sport' },
    { word: 'Hoelahoep', category: 'Sport' },
    { word: 'Touwtjespringen', category: 'Sport' },
    { word: 'Verstoppertje', category: 'Sport' },
    { word: 'Twister', category: 'Sport' },
    { word: 'Skeeleren', category: 'Sport' },
    { word: 'Snowboarden', category: 'Sport' },
    { word: 'Waterpolo', category: 'Sport' },
    { word: 'Kogelstoten', category: 'Sport' },
    { word: 'Hoogspringen', category: 'Sport' },
    { word: 'Voetbal', category: 'Sport' },
    { word: 'Basketbal', category: 'Sport' },
    { word: 'Volleybal', category: 'Sport' },
    { word: 'Tennis', category: 'Sport' },
    { word: 'Tafeltennis', category: 'Sport' },
    { word: 'Badminton', category: 'Sport' },
    { word: 'Hockey', category: 'Sport' },
    { word: 'Honkbal', category: 'Sport' },
    { word: 'Rugby', category: 'Sport' },
    { word: 'Handbal', category: 'Sport' },
    { word: 'Worstelen', category: 'Sport' },
    { word: 'Gewichtheffen', category: 'Sport' },
    { word: 'Speerwerpen', category: 'Sport' },
    { word: 'Discuswerpen', category: 'Sport' },
    { word: 'Polsstokspringen', category: 'Sport' },
    { word: 'Hordelopen', category: 'Sport' },
    { word: 'Marathon', category: 'Sport' },
    { word: 'Schaken', category: 'Sport' },
    { word: 'Biljarten', category: 'Sport' },
    { word: 'Jeu de boules', category: 'Sport' },
    { word: 'Trefbal', category: 'Sport' },
    { word: 'Zaklopen', category: 'Sport' },
    { word: 'Titanic', category: 'Film & TV' },
    { word: 'Jaws', category: 'Film & TV' },
    { word: 'Harry Potter', category: 'Film & TV' },
    { word: 'Spiderman', category: 'Film & TV' },
    { word: 'Superman', category: 'Film & TV' },
    { word: 'Batman', category: 'Film & TV' },
    { word: 'King Kong', category: 'Film & TV' },
    { word: 'Frozen', category: 'Film & TV' },
    { word: 'Jurassic Park', category: 'Film & TV' },
    { word: 'Rocky', category: 'Film & TV' },
    { word: 'The Lion King', category: 'Film & TV' },
    { word: 'Star Wars', category: 'Film & TV' },
    { word: 'Shrek', category: 'Film & TV' },
    { word: 'Finding Nemo', category: 'Film & TV' },
    { word: 'Bassie en Adriaan', category: 'Film & TV' },
    { word: 'Nijntje', category: 'Film & TV' },
    { word: 'Kuifje', category: 'Film & TV' },
    { word: 'Pipi Langkous', category: 'Film & TV' },
    { word: 'Wie is de Mol', category: 'Film & TV' },
    { word: 'Expeditie Robinson', category: 'Film & TV' },
    { word: 'Boer zoekt Vrouw', category: 'Film & TV' },
    { word: 'Baywatch', category: 'Film & TV' },
    { word: 'Mr. Bean', category: 'Film & TV' },
    { word: 'Charlie Chaplin', category: 'Film & TV' },
    { word: 'E.T.', category: 'Film & TV' },
    { word: 'Terminator', category: 'Film & TV' },
    { word: 'James Bond', category: 'Film & TV' },
    { word: 'Indiana Jones', category: 'Film & TV' },
    { word: 'Pirates of the Caribbean', category: 'Film & TV' },
    { word: 'Mission Impossible', category: 'Film & TV' },
    { word: 'The Matrix', category: 'Film & TV' },
    { word: 'Ghostbusters', category: 'Film & TV' },
    { word: 'Home Alone', category: 'Film & TV' },
    { word: 'Tarzan', category: 'Film & TV' },
    { word: 'Pinokkio', category: 'Film & TV' },
    { word: 'Sneeuwwitje', category: 'Film & TV' },
    { word: 'Assepoester', category: 'Film & TV' },
    { word: 'De Kleine Zeemeermin', category: 'Film & TV' },
    { word: 'Mickey Mouse', category: 'Film & TV' },
    { word: 'Donald Duck', category: 'Film & TV' },
    { word: 'Usain Bolt', category: 'Beroemd' },
    { word: 'Max Verstappen', category: 'Beroemd' },
    { word: 'Johan Cruijff', category: 'Beroemd' },
    { word: 'Sinterklaas', category: 'Beroemd' },
    { word: 'Kerstman', category: 'Beroemd' },
    { word: 'Napoleon', category: 'Beroemd' },
    { word: 'Einstein', category: 'Beroemd' },
    { word: 'Elvis', category: 'Beroemd' },
    { word: 'Dracula', category: 'Beroemd' },
    { word: 'Robin Hood', category: 'Beroemd' },
    { word: 'Zorro', category: 'Beroemd' },
    { word: 'Jezus', category: 'Beroemd' },
    { word: 'Koning Willem-Alexander', category: 'Beroemd' },
    { word: 'Paus', category: 'Beroemd' },
    { word: 'Freddie Mercury', category: 'Beroemd' },
    { word: 'André Hazes', category: 'Beroemd' },
    { word: 'Kabouter Plop', category: 'Beroemd' },
    { word: 'Michael Jackson', category: 'Beroemd' },
    { word: 'Zwarte Piet', category: 'Beroemd' },
    { word: 'Rembrandt', category: 'Beroemd' },
    { word: 'Van Gogh', category: 'Beroemd' },
    { word: 'Cleopatra', category: 'Beroemd' },
    { word: 'Julius Caesar', category: 'Beroemd' },
    { word: 'Frankenstein', category: 'Beroemd' },
    { word: 'Sherlock Holmes', category: 'Beroemd' },
    { word: 'Popeye', category: 'Beroemd' },
    { word: 'Hulk', category: 'Beroemd' },
    { word: 'Pietje Bell', category: 'Beroemd' },
    { word: 'Sjakie de piraat', category: 'Beroemd' },
    { word: 'Doutzen Kroes', category: 'Beroemd' },
    { word: 'Verliefd', category: 'Emotie' },
    { word: 'Verveeld', category: 'Emotie' },
    { word: 'Dronken', category: 'Emotie' },
    { word: 'Zenuwachtig', category: 'Emotie' },
    { word: 'Jaloers', category: 'Emotie' },
    { word: 'Trots', category: 'Emotie' },
    { word: 'Kwaad', category: 'Emotie' },
    { word: 'Verlegen', category: 'Emotie' },
    { word: 'Bang', category: 'Emotie' },
    { word: 'Uitgeput', category: 'Emotie' },
    { word: 'Zeeziek', category: 'Emotie' },
    { word: 'Verbaasd', category: 'Emotie' },
    { word: 'Blij', category: 'Emotie' },
    { word: 'Verdrietig', category: 'Emotie' },
    { word: 'Ongeduldig', category: 'Emotie' },
    { word: 'Opgelucht', category: 'Emotie' },
    { word: 'Verward', category: 'Emotie' },
    { word: 'Beledigd', category: 'Emotie' },
    { word: 'Bevroren van de kou', category: 'Emotie' },
    { word: 'Misselijk', category: 'Emotie' },
];
