/** Content and helpers for the Forbidden Word (Taboo-style) game. */

export interface ForbiddenCard {
    /** The word the player must get the group to guess. */
    word: string;
    /** Words that may not be used while describing. */
    forbidden: string[];
}

/** Inclusive bounds for the number of players. */
export const MIN_PLAYERS = 2;
export const MAX_PLAYERS = 12;

/** Turn lengths offered in setup, in seconds. */
export const TURN_SECONDS_OPTIONS = [30, 60, 90] as const;

/** How many turns each player gets, offered in setup. */
export const ROUNDS_OPTIONS = [2, 3, 4] as const;

export const CARDS: ForbiddenCard[] = [
    { word: 'Strand', forbidden: ['Zee', 'Zand', 'Zon', 'Vakantie'] },
    { word: 'Voetbal', forbidden: ['Bal', 'Doel', 'Sport', 'Veld'] },
    { word: 'Pizza', forbidden: ['Italië', 'Kaas', 'Deeg', 'Eten'] },
    { word: 'Kerstmis', forbidden: ['Kerstman', 'Cadeau', 'Boom', 'December'] },
    { word: 'Trein', forbidden: ['Spoor', 'Station', 'Rails', 'NS'] },
    { word: 'Telefoon', forbidden: ['Bellen', 'Mobiel', 'App', 'Scherm'] },
    { word: 'Koffie', forbidden: ['Drinken', 'Cafeïne', 'Bonen', 'Wakker'] },
    { word: 'Hond', forbidden: ['Blaffen', 'Huisdier', 'Poes', 'Baas'] },
    { word: 'Dokter', forbidden: ['Ziek', 'Ziekenhuis', 'Patiënt', 'Wit'] },
    { word: 'Verjaardag', forbidden: ['Taart', 'Feest', 'Cadeau', 'Jarig'] },
    { word: 'Sneeuw', forbidden: ['Wit', 'Koud', 'Winter', 'Vlok'] },
    { word: 'Vliegtuig', forbidden: ['Vliegen', 'Lucht', 'Piloot', 'Vakantie'] },
    { word: 'Boek', forbidden: ['Lezen', 'Pagina', 'Verhaal', 'Bibliotheek'] },
    { word: 'Gitaar', forbidden: ['Muziek', 'Snaar', 'Spelen', 'Band'] },
    { word: 'Regen', forbidden: ['Water', 'Paraplu', 'Nat', 'Wolk'] },
    { word: 'Kapper', forbidden: ['Haar', 'Knippen', 'Schaar', 'Kapsel'] },
    { word: 'Supermarkt', forbidden: ['Boodschappen', 'Winkel', 'Karretje', 'Kassa'] },
    { word: 'Zwembad', forbidden: ['Water', 'Zwemmen', 'Bad', 'Nat'] },
    { word: 'Politie', forbidden: ['Agent', 'Boef', 'Auto', 'Wet'] },
    { word: 'Tandarts', forbidden: ['Tand', 'Boren', 'Mond', 'Pijn'] },
    { word: 'Fiets', forbidden: ['Wiel', 'Trappen', 'Bel', 'Rijden'] },
    { word: 'Sinterklaas', forbidden: ['Piet', 'Pakjes', 'Schoen', 'Boot'] },
    { word: 'Chocolade', forbidden: ['Bruin', 'Zoet', 'Snoep', 'Reep'] },
    { word: 'Computer', forbidden: ['Scherm', 'Toetsenbord', 'Internet', 'Muis'] },
    { word: 'Voetballer', forbidden: ['Voetbal', 'Speler', 'Doelpunt', 'Club'] },
    { word: 'Bioscoop', forbidden: ['Film', 'Popcorn', 'Scherm', 'Kaartje'] },
    { word: 'Paraplu', forbidden: ['Regen', 'Nat', 'Open', 'Stok'] },
    { word: 'Vuurwerk', forbidden: ['Oudjaar', 'Knal', 'Lucht', 'Knallen'] },
    { word: 'Kameel', forbidden: ['Woestijn', 'Bult', 'Dier', 'Zand'] },
    { word: 'Pannenkoek', forbidden: ['Stroop', 'Bakken', 'Plat', 'Beslag'] },
    { word: 'Brandweer', forbidden: ['Vuur', 'Blussen', 'Slang', 'Rood'] },
    { word: 'Verkering', forbidden: ['Liefde', 'Vriend', 'Relatie', 'Kus'] },

    { word: 'Vork', forbidden: ['Eten', 'Bestek', 'Prikken', 'Mes'] },
    { word: 'Lepel', forbidden: ['Soep', 'Eten', 'Bestek', 'Roeren'] },
    { word: 'Mes', forbidden: ['Snijden', 'Scherp', 'Bestek', 'Brood'] },
    { word: 'Bord', forbidden: ['Eten', 'Rond', 'Tafel', 'Servies'] },
    { word: 'Glas', forbidden: ['Drinken', 'Water', 'Breekbaar', 'Doorzichtig'] },
    { word: 'Stoel', forbidden: ['Zitten', 'Poten', 'Tafel', 'Meubel'] },
    { word: 'Tafel', forbidden: ['Eten', 'Poten', 'Stoel', 'Hout'] },
    { word: 'Bed', forbidden: ['Slapen', 'Matras', 'Kussen', 'Nacht'] },
    { word: 'Kussen', forbidden: ['Slapen', 'Hoofd', 'Zacht', 'Bed'] },
    { word: 'Deken', forbidden: ['Warm', 'Bed', 'Slapen', 'Dekken'] },
    { word: 'Lamp', forbidden: ['Licht', 'Donker', 'Aan', 'Schijnen'] },
    { word: 'Spiegel', forbidden: ['Kijken', 'Reflectie', 'Glas', 'Gezicht'] },
    { word: 'Klok', forbidden: ['Tijd', 'Uur', 'Wijzers', 'Tikken'] },
    { word: 'Deur', forbidden: ['Open', 'Sluiten', 'Klink', 'Kamer'] },
    { word: 'Raam', forbidden: ['Glas', 'Kijken', 'Buiten', 'Open'] },
    { word: 'Trap', forbidden: ['Treden', 'Omhoog', 'Lopen', 'Verdieping'] },
    { word: 'Sleutel', forbidden: ['Slot', 'Deur', 'Openen', 'Slotje'] },
    { word: 'Tas', forbidden: ['Dragen', 'Hengsel', 'Spullen', 'Schouder'] },
    { word: 'Schoen', forbidden: ['Voet', 'Lopen', 'Veters', 'Dragen'] },
    { word: 'Sok', forbidden: ['Voet', 'Schoen', 'Warm', 'Wol'] },
    { word: 'Broek', forbidden: ['Benen', 'Dragen', 'Riem', 'Kleding'] },
    { word: 'Jas', forbidden: ['Warm', 'Winter', 'Dragen', 'Kleding'] },
    { word: 'Hoed', forbidden: ['Hoofd', 'Dragen', 'Rand', 'Zon'] },
    { word: 'Bril', forbidden: ['Zien', 'Ogen', 'Glazen', 'Neus'] },
    { word: 'Handschoen', forbidden: ['Hand', 'Warm', 'Vingers', 'Winter'] },
    { word: 'Sjaal', forbidden: ['Nek', 'Warm', 'Winter', 'Wol'] },
    { word: 'Hand', forbidden: ['Vingers', 'Arm', 'Grijpen', 'Lichaam'] },
    { word: 'Voet', forbidden: ['Tenen', 'Been', 'Lopen', 'Schoen'] },
    { word: 'Oog', forbidden: ['Zien', 'Kijken', 'Gezicht', 'Wimpers'] },
    { word: 'Neus', forbidden: ['Ruiken', 'Gezicht', 'Snuiten', 'Geur'] },
    { word: 'Oor', forbidden: ['Horen', 'Geluid', 'Hoofd', 'Luisteren'] },
    { word: 'Tand', forbidden: ['Mond', 'Bijten', 'Wit', 'Poetsen'] },
    { word: 'Haar', forbidden: ['Hoofd', 'Kammen', 'Knippen', 'Kapper'] },
    { word: 'Appel', forbidden: ['Fruit', 'Rood', 'Boom', 'Eten'] },
    { word: 'Banaan', forbidden: ['Geel', 'Fruit', 'Schil', 'Aap'] },
    { word: 'Aardbei', forbidden: ['Rood', 'Fruit', 'Zoet', 'Zaadjes'] },
    { word: 'Sinaasappel', forbidden: ['Oranje', 'Fruit', 'Sap', 'Schil'] },
    { word: 'Brood', forbidden: ['Bakker', 'Snijden', 'Boterham', 'Korst'] },
    { word: 'Kaas', forbidden: ['Geel', 'Melk', 'Gaten', 'Boterham'] },
    { word: 'Melk', forbidden: ['Koe', 'Wit', 'Drinken', 'Glas'] },
    { word: 'Ei', forbidden: ['Kip', 'Schaal', 'Bakken', 'Geel'] },
    { word: 'Soep', forbidden: ['Lepel', 'Warm', 'Kom', 'Groente'] },
    { word: 'Patat', forbidden: ['Aardappel', 'Frituur', 'Mayonaise', 'Zout'] },
    { word: 'Stroopwafel', forbidden: ['Koek', 'Siroop', 'Rond', 'Zoet'] },
    { word: 'Haring', forbidden: ['Vis', 'Zout', 'Ui', 'Rauw'] },
    { word: 'Thee', forbidden: ['Drinken', 'Warm', 'Zakje', 'Water'] },
    { word: 'Suiker', forbidden: ['Zoet', 'Wit', 'Koffie', 'Klontje'] },
    { word: 'Zout', forbidden: ['Strooien', 'Smaak', 'Wit', 'Peper'] },
    { word: 'Boter', forbidden: ['Brood', 'Smeren', 'Geel', 'Vet'] },
    { word: 'Honing', forbidden: ['Bij', 'Zoet', 'Plakkerig', 'Goud'] },
    { word: 'IJs', forbidden: ['Koud', 'Zomer', 'Hoorntje', 'Likken'] },
    { word: 'Kerk', forbidden: ['Toren', 'Geloof', 'Gebed', 'Klok'] },
    { word: 'Ziekenhuis', forbidden: ['Dokter', 'Ziek', 'Bed', 'Patiënt'] },
    { word: 'School', forbidden: ['Leren', 'Juf', 'Klas', 'Kinderen'] },
    { word: 'Markt', forbidden: ['Kraam', 'Kopen', 'Plein', 'Groente'] },
    { word: 'Brug', forbidden: ['Water', 'Oversteken', 'Rivier', 'Verbinding'] },
    { word: 'Molen', forbidden: ['Wieken', 'Wind', 'Draaien', 'Nederland'] },
    { word: 'Kasteel', forbidden: ['Ridder', 'Toren', 'Gracht', 'Koning'] },
    { word: 'Boerderij', forbidden: ['Koe', 'Boer', 'Dieren', 'Land'] },
    { word: 'Berg', forbidden: ['Hoog', 'Klimmen', 'Top', 'Dal'] },
    { word: 'Rivier', forbidden: ['Water', 'Stromen', 'Oever', 'Vis'] },
    { word: 'Bos', forbidden: ['Bomen', 'Groen', 'Wandelen', 'Dieren'] },
    { word: 'Bliksem', forbidden: ['Onweer', 'Licht', 'Lucht', 'Flits'] },
    { word: 'Wind', forbidden: ['Waaien', 'Lucht', 'Hard', 'Storm'] },
    { word: 'Wolk', forbidden: ['Lucht', 'Wit', 'Hemel', 'Regen'] },
    { word: 'Zon', forbidden: ['Warm', 'Licht', 'Geel', 'Hemel'] },
    { word: 'Maan', forbidden: ['Nacht', 'Rond', 'Hemel', 'Licht'] },
    { word: 'Bloem', forbidden: ['Tuin', 'Geur', 'Blaadjes', 'Plukken'] },
    { word: 'Boom', forbidden: ['Blad', 'Stam', 'Tak', 'Bos'] },
    { word: 'Vlinder', forbidden: ['Vleugels', 'Fladderen', 'Rups', 'Bloem'] },
    { word: 'Tennis', forbidden: ['Racket', 'Net', 'Bal', 'Baan'] },
    { word: 'Zwemmen', forbidden: ['Water', 'Bad', 'Zwembad', 'Crawl'] },
    { word: 'Wielrennen', forbidden: ['Fiets', 'Trappen', 'Wedstrijd', 'Helm'] },
    { word: 'Boksen', forbidden: ['Handschoenen', 'Ring', 'Stoten', 'Vechten'] },
    { word: 'Schaatsen', forbidden: ['IJs', 'Glijden', 'Winter', 'Baan'] },
    { word: 'Basketbal', forbidden: ['Bal', 'Ring', 'Korf', 'Dunk'] },
    { word: 'Hockey', forbidden: ['Stick', 'Bal', 'Veld', 'Doel'] },
    { word: 'Golf', forbidden: ['Stok', 'Bal', 'Hole', 'Gras'] },
    { word: 'Skiën', forbidden: ['Sneeuw', 'Berg', 'Latten', 'Piste'] },
    { word: 'Marathon', forbidden: ['Hardlopen', 'Kilometer', 'Finish', 'Lang'] },
    { word: 'Yoga', forbidden: ['Houding', 'Ademen', 'Mat', 'Ontspannen'] },
    { word: 'Schilderen', forbidden: ['Verf', 'Kwast', 'Doek', 'Kunst'] },
    { word: 'Tuinieren', forbidden: ['Planten', 'Tuin', 'Bloemen', 'Spitten'] },
    { word: 'Fotografie', forbidden: ['Camera', 'Foto', 'Lens', 'Kiekje'] },
    { word: 'Koken', forbidden: ['Pan', 'Eten', 'Keuken', 'Recept'] },
    { word: 'Breien', forbidden: ['Wol', 'Naalden', 'Trui', 'Steken'] },
    { word: 'Vissen', forbidden: ['Hengel', 'Water', 'Vis', 'Aas'] },
    { word: 'Dansen', forbidden: ['Muziek', 'Bewegen', 'Vloer', 'Ritme'] },
    { word: 'Lezen', forbidden: ['Boek', 'Bladzijde', 'Verhaal', 'Letters'] },
    { word: 'Schaken', forbidden: ['Bord', 'Koning', 'Stukken', 'Mat'] },
    { word: 'Leraar', forbidden: ['School', 'Les', 'Klas', 'Leerlingen'] },
    { word: 'Bakker', forbidden: ['Brood', 'Oven', 'Deeg', 'Winkel'] },
    { word: 'Piloot', forbidden: ['Vliegtuig', 'Vliegen', 'Cockpit', 'Lucht'] },
    { word: 'Slager', forbidden: ['Vlees', 'Mes', 'Worst', 'Winkel'] },
    { word: 'Tuinman', forbidden: ['Tuin', 'Planten', 'Snoeien', 'Gras'] },
    { word: 'Verpleegster', forbidden: ['Ziekenhuis', 'Patiënt', 'Zorg', 'Wit'] },
    { word: 'Advocaat', forbidden: ['Rechtbank', 'Wet', 'Verdedigen', 'Rechter'] },
    { word: 'Boer', forbidden: ['Koeien', 'Land', 'Tractor', 'Boerderij'] },
    { word: 'Visser', forbidden: ['Boot', 'Net', 'Vis', 'Zee'] },
    { word: 'Schilder', forbidden: ['Verf', 'Kwast', 'Muur', 'Ladder'] },
    { word: 'Olifant', forbidden: ['Slurf', 'Groot', 'Grijs', 'Slagtanden'] },
    { word: 'Pinguïn', forbidden: ['IJs', 'Zwart', 'Zuidpool', 'Waggelen'] },
    { word: 'Giraffe', forbidden: ['Nek', 'Lang', 'Vlekken', 'Afrika'] },
    { word: 'Kangoeroe', forbidden: ['Springen', 'Buidel', 'Australië', 'Staart'] },
    { word: 'Krokodil', forbidden: ['Tanden', 'Water', 'Reptiel', 'Bek'] },
    { word: 'Egel', forbidden: ['Stekels', 'Bolletje', 'Prik', 'Klein'] },
    { word: 'Dolfijn', forbidden: ['Zee', 'Zwemmen', 'Slim', 'Springen'] },
    { word: 'Uil', forbidden: ['Nacht', 'Vogel', 'Wijs', 'Ogen'] },
    { word: 'Beer', forbidden: ['Bos', 'Honing', 'Bruin', 'Winterslaap'] },
    { word: 'Concert', forbidden: ['Muziek', 'Band', 'Podium', 'Publiek'] },
    { word: 'Toneel', forbidden: ['Podium', 'Acteur', 'Spelen', 'Theater'] },
    { word: 'Orkest', forbidden: ['Muziek', 'Dirigent', 'Instrumenten', 'Viool'] },
    { word: 'Cabaret', forbidden: ['Grappig', 'Podium', 'Lachen', 'Voorstelling'] },
    { word: 'Festival', forbidden: ['Muziek', 'Tent', 'Optreden', 'Weekend'] },
    { word: 'Circus', forbidden: ['Clown', 'Tent', 'Acrobaat', 'Manege'] },
    { word: 'Museum', forbidden: ['Kunst', 'Schilderij', 'Tentoonstelling', 'Zaal'] },
    { word: 'Karaoke', forbidden: ['Zingen', 'Microfoon', 'Liedje', 'Scherm'] },
    { word: 'Pasen', forbidden: ['Eieren', 'Haas', 'Zoeken', 'Lente'] },
    { word: 'Oudjaar', forbidden: ['Champagne', 'Middernacht', 'Jaar', 'Feest'] },
    { word: 'Carnaval', forbidden: ['Verkleden', 'Optocht', 'Feest', 'Maskers'] },
    { word: 'Koningsdag', forbidden: ['Oranje', 'Vrijmarkt', 'Koning', 'Feest'] },
    { word: 'Bruiloft', forbidden: ['Trouwen', 'Jurk', 'Ringen', 'Feest'] },
    { word: 'Halloween', forbidden: ['Spoken', 'Pompoen', 'Eng', 'Snoep'] },
    { word: 'Helikopter', forbidden: ['Wieken', 'Vliegen', 'Lucht', 'Landen'] },
    { word: 'Onderzeeër', forbidden: ['Water', 'Duiken', 'Diep', 'Zee'] },
    { word: 'Tram', forbidden: ['Rails', 'Stad', 'Halte', 'Bovenleiding'] },
    { word: 'Ballon', forbidden: ['Lucht', 'Mand', 'Stijgen', 'Gas'] },
    { word: 'Motor', forbidden: ['Rijden', 'Helm', 'Wielen', 'Gas'] },
    { word: 'Boot', forbidden: ['Water', 'Varen', 'Zee', 'Roer'] },
    { word: 'Geluk', forbidden: ['Blij', 'Vrolijk', 'Gevoel', 'Lachen'] },
    { word: 'Angst', forbidden: ['Bang', 'Vrees', 'Gevoel', 'Beven'] },
    { word: 'Liefde', forbidden: ['Hart', 'Verliefd', 'Gevoel', 'Romantiek'] },
    { word: 'Vrijheid', forbidden: ['Vrij', 'Kunnen', 'Keuze', 'Gevangenis'] },
    { word: 'Tijd', forbidden: ['Klok', 'Uur', 'Minuut', 'Verstrijken'] },
    { word: 'Dromen', forbidden: ['Slapen', 'Nacht', 'Bed', 'Fantasie'] },
    { word: 'Geheim', forbidden: ['Stil', 'Niemand', 'Verbergen', 'Fluisteren'] },
];

/** Picks a random card, optionally avoiding the previous one. */
export function pickCard(avoid?: ForbiddenCard): ForbiddenCard {
    if (CARDS.length <= 1) {
        return CARDS[0];
    }

    let choice = CARDS[Math.floor(Math.random() * CARDS.length)];

    while (choice.word === avoid?.word) {
        choice = CARDS[Math.floor(Math.random() * CARDS.length)];
    }

    return choice;
}
